apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tomcat-main
  labels:
    app: tomcat-main
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat-main
        tier: frontend
    spec:
      containers:
      - name: main-frontend
        image: seniorlogistica/gwt-main-frontend:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tomcat-wms-storage
          mountPath: "/usr/local/tomcat/webapps"
      volumes:
        - hostPath:
            path: "/data/tomcat/"
          name: tomcat-wms-storage
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-main-svc
spec:
  selector:
    app: tomcat-main
    tier: frontend
  ports:
    - port: 8088
      targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wms-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: tomcat-main-svc
          servicePort: 8088